### ISSUE TITLE
continue-example-list option

### ISSUE THREAD

**Issue by jdutant** [dialoa/collection#5]
Provide an option to continue example lists from one source to another

**Comment by twsh** [comment]
Just to note that it needs to handle the references to the examples too.

**Comment by jdutant** [comment]
Good point. Looks like that won't be possible, unfortunately. See the json:

```json
{"pandoc-api-version":[1,22],"meta":{},"blocks":[{"t":"OrderedList","c":[[1,{"t":"Example"},{"t":"TwoParens"}],[[{"t":"Plain","c":[{"t":"Str","c":"This"},{"t":"Space"},{"t":"Str","c":"is"},{"t":"Space"},{"t":"Str","c":"a"},{"t":"Space"},{"t":"Str","c":"good"},{"t":"Space"},{"t":"Str","c":"example."}]}]]]},{"t":"Para","c":[{"t":"Str","c":"As"},{"t":"Space"},{"t":"Str","c":"(1)"},{"t":"Space"},{"t":"Str","c":"illustrates,"},{"t":"Space"},{"t":"Str","c":"…"}]}]}
```

The reference `@good` has already been converted to (1). The problem is that numbered lists don't have identifiers. The only thing the AST has is the type (Example) and the starting number (1). Hopefully that's fixed in future versions of the AST, there's talk of allowing identifiers to any/most elements. 

Barring processing the source before Pandoc parses it, or trying to guess which (1) where cross-references and which weren't, I don't see a way.

Given this, not sure it's worth implementing the option. Users won't understand why it breaks down; better say that continous lists across sources aren't possible.

**Comment by twsh** [comment]
I think that's right.

For reference, it might be possible to get such lists by using this instead of Pandoc's support for examples: [https://github.com/cysouw/pandoc-ling](https://github.com/cysouw/pandoc-ling).

**Comment by jdutant** [comment]
Yes this is much better. 

One use for numbered examples in a Dialectica paper was for someone who had continuously numbered items throughout their paper, where the items where sometimes several blocks long (including a table, an indentend argument, and the like!). It kind of almost works with numbered examples (though it looks as if we've got a blank line where the item starts with a Div). I wonder if pandoc-ling (and whatever LaTeX it uses) can handle that too, or is restricted to one-block items. If yes we might use it instead of Pandoc's internal mechanism in all cases.
